--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA LAB11_202!

CREATE TABLE LAB11_202.Product (
		pid CHAR(5) NOT NULL,
		pname VARCHAR(32)
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB11_202.Supplier (
		sid CHAR(5) NOT NULL,
		sname VARCHAR(32)
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB11_202.Supply (
		pid CHAR(5) NOT NULL,
		sid CHAR(5) NOT NULL,
		qty SMALLINT NOT NULL
	)
	DATA CAPTURE NONE!

ALTER TABLE LAB11_202.Product ADD CONSTRAINT Product_PK PRIMARY KEY
	(pid)!

ALTER TABLE LAB11_202.Supplier ADD CONSTRAINT Supplier_PK PRIMARY KEY
	(sid)!

ALTER TABLE LAB11_202.Supply ADD CONSTRAINT Supply_PK PRIMARY KEY
	(pid,
	 sid)!

ALTER TABLE LAB11_202.Supply ADD CONSTRAINT Supply_Product_FK FOREIGN KEY
	(pid)
	REFERENCES LAB11_202.Product
	(pid)
	ON DELETE CASCADE!

ALTER TABLE LAB11_202.Supply ADD CONSTRAINT Supply_Supplier_FK FOREIGN KEY
	(sid)
	REFERENCES LAB11_202.Supplier
	(sid)
	ON DELETE CASCADE!

