--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA LAB1B_202!

CREATE TABLE LAB1B_202.Student (
		Reg_no CHAR(5) NOT NULL,
		Name VARCHAR(32),
		Major VARCHAR(32),
		Bdate DATE
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB1B_202.Course (
		Course_ID CHAR(5) NOT NULL,
		Cname VARCHAR(32),
		Dept VARCHAR(32)
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB1B_202.Enroll (
		Reg_no CHAR(5) NOT NULL,
		Course_ID CHAR(5) NOT NULL,
		Marks SMALLINT
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB1B_202.Book_Adoption (
		Course_ID CHAR(5) NOT NULL,
		Sem SMALLINT NOT NULL,
		ISBN CHAR(13) NOT NULL
	)
	DATA CAPTURE NONE!

CREATE TABLE LAB1B_202.Book (
		ISBN CHAR(13) NOT NULL,
		Title VARCHAR(32),
		Publisher VARCHAR(32),
		Author VARCHAR(32)
	)
	DATA CAPTURE NONE!

ALTER TABLE LAB1B_202.Student ADD CONSTRAINT Student_PK PRIMARY KEY
	(Reg_no)!

ALTER TABLE LAB1B_202.Course ADD CONSTRAINT Course_PK PRIMARY KEY
	(Course_ID)!

ALTER TABLE LAB1B_202.Enroll ADD CONSTRAINT Enroll_PK PRIMARY KEY
	(Reg_no,
	 Course_ID)!

ALTER TABLE LAB1B_202.Book_Adoption ADD CONSTRAINT Book_Adoption_PK PRIMARY KEY
	(Course_ID,
	 ISBN)!

ALTER TABLE LAB1B_202.Book ADD CONSTRAINT Book_PK PRIMARY KEY
	(ISBN)!

ALTER TABLE LAB1B_202.Enroll ADD CONSTRAINT Enroll_Student_FK FOREIGN KEY
	(Reg_no)
	REFERENCES LAB1B_202.Student
	(Reg_no)
	ON DELETE CASCADE!

ALTER TABLE LAB1B_202.Enroll ADD CONSTRAINT Enroll_Course_FK FOREIGN KEY
	(Course_ID)
	REFERENCES LAB1B_202.Course
	(Course_ID)
	ON DELETE CASCADE!

ALTER TABLE LAB1B_202.Book_Adoption ADD CONSTRAINT Book_Adoption_Course_FK FOREIGN KEY
	(Course_ID)
	REFERENCES LAB1B_202.Course
	(Course_ID)
	ON DELETE CASCADE!

ALTER TABLE LAB1B_202.Book_Adoption ADD CONSTRAINT Book_Adoption_Book_FK FOREIGN KEY
	(ISBN)
	REFERENCES LAB1B_202.Book
	(ISBN)
	ON DELETE CASCADE!

