--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA 202_LAB1A!

CREATE TABLE 202_LAB1A.Product (
		pid CHAR(5) NOT NULL,
		pname VARCHAR(32)
	)
	DATA CAPTURE NONE!

CREATE TABLE 202_LAB1A.Supplier (
		sid CHAR(5) NOT NULL,
		sname VARCHAR(32)
	)
	DATA CAPTURE NONE!

CREATE TABLE 202_LAB1A.Supply (
		pid CHAR(5) NOT NULL,
		sid CHAR(5) NOT NULL,
		qty SMALLINT NOT NULL
	)
	DATA CAPTURE NONE!

ALTER TABLE 202_LAB1A.Product ADD CONSTRAINT Product_PK PRIMARY KEY
	(pid)!

ALTER TABLE 202_LAB1A.Supplier ADD CONSTRAINT Supplier_PK PRIMARY KEY
	(sid)!

